version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: express_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_starter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - express_network

volumes:
  postgres_data:

networks:
  express_network:
    driver: bridge